sudo: required
services:
  - docker

before_install:
  - docker build -t unit -f Dockerfile.dev .
  - docker build -t acceptance -f Dockerfile.dev .

script:
  - docker run unit npm run test -- --coverage
  - docker run acceptance npm run acceptance -- --forceExit
